### PR TITLE
update v6 alphas

### LINKED ISSUE #46: react-console: Consume v6 alphas and build Penta demo
This will be especially powerful once the v6 Classic theme is done, so that the following deprecated components can exist alongside themed/non-deprecated components without any style clashing:
- [ ] Dropdown-deprecated (Dropdown-deprecate,DropdownItem-deprecated,DropdownToggle-deprecated)
- [ ] Select-deprecated (Select-deprecated,SelectOptionObject-deprecated,SelectVariant-deprecated)

Once the official alpha is announced, it should be pulled in to user feedback's v6 branch.

Once feedback is given regarding how the deprecated components behaved throughout the migration, an issue should be opened as a follow up (and addressed ASAP) to remove usage of deprecated components.

The v6 branch should also be updated to include all changes made to the main branch since the v6 branch was created.

Once the code merges and a v6-alpha of this extension is available, it should be pulled into the v6 branch on org.

### PR DESCRIPTION
**Pull request by kmcfaul**
Closes #46.

- Updates to latest v6 alpha versions
- Fixes EmptyState structure change - as there was no header text, body text was pulled up into the title
- Updates usages of v5 to v6 classes (`pf-v6-c-console__xterm` doesn't seem to exist, did we have a v5 for this or was it always just a placeholder? @mcoker)
- Updates build commands to include watch
- Updates snapshots

### CODE REVIEW

**Comment by mcoker** [comment]
> Updates usages of v5 to v6 classes (`pf-v6-c-console__xterm` doesn't seem to exist, did we have a v5 for this or was it always just a placeholder? @mcoker)

That class doesn't come from core - there are no `*-c-console*` classes/vars/etc

**Comment by kmcfaul** [comment]
They must come directly from `react-styles` then, will take a look.

**Comment by dlabaj** [comment]
@kmcfaul Can you do post the Patternfly document to surge and include it in this PR so design can see the updates.

**Comment by kmcfaul** [comment]
Here is the surge - https://windy-clocks-47747.surge.sh/

**Review by nicolethoen — APPROVED** [review]
From what I can tell, the console is behaving the same way in your preview that it does on patternfly.org right now. 

I know react-console has some styles which are defined and live in @patternfly/react-styles, so we should open a follow up issue for this PR to make sure those are all using the tokens correctly (and then an additional follow up here to consume the latest react-styles version).

But i don't see anything here IMO that would block this from merging as an alpha :)

**Review by andrew-ronaldson — APPROVED** [review]
Looks good to me. thanks!

**Review by dlabaj — APPROVED** [review]
LGTM

**Pull request merged**
